# Generated by Django 5.1.7 on 2025-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='room_banners/'),
        ),
    ]
