# Generated by Django 5.1.7 on 2025-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='banner',
            field=models.ImageField(blank=True, default='room_banner.png', null=True, upload_to='room_banners/'),
        ),
    ]
