# Generated by Django 5.1.7 on 2025-03-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_audiomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomessage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiomessage_set', to='base.message'),
        ),
    ]
