# Generated by Django 5.1.7 on 2025-03-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='banner',
        ),
    ]
