# Generated by Django 5.1.7 on 2025-03-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='creator',
        ),
    ]
